# General project definition
sonar.projectKey=WhakerPy
sonar.projectName=WhakerPy
sonar.projectVersion=0.8
sonar.organization=LPL

# Path is relative to the sonar-project.properties file. Defaults to .
sonar.sources=whakerpy

# Unit tests
sonar.tests=tests
sonar.python.coverage.reportPaths=tests/coverage.xml

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Files or directories to exclude.
sonar.exclusions=**/tests/**

# Language for the Python analyzer
sonar.language=py
sonar.python.version=3.9, 3.10, 3.11, 3.12

# SonarQube server URL
sonar.host.url=http://localhost:9000
